import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('../agent_world/web/stream-client.js',import.meta.url),'utf8');
const {BubbleQueue}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const msg=(id,subject='a',expires_at=108)=>({id,subject,text:'hello',at:100,expires_at});
let q=new BubbleQueue();
q.push(msg('a1'),100); q.push(msg('a2'),100);
assert.equal(q.active(100)[0].id,'a1');
assert.deepEqual(q.active(110),[], 'expired queued messages must never start');
q=new BubbleQueue();q.push(msg('a'),106);
assert.equal(q.active(106)[0].until,108,'visible lifetime cannot exceed absolute expiry');
assert.deepEqual(q.active(108),[]);
q=new BubbleQueue();assert.equal(q.push(msg('expired'),109),false);
assert.equal(q.push(msg('too-short'),107.5),false);
assert.equal(q.push({...msg('invalid'),expires_at:NaN},100),false);
q=new BubbleQueue({maxVisible:1});q.push(msg('old','a'),100);q.push(msg('new','b',120),100);
assert.equal(q.active(100)[0].id,'old');
assert.equal(q.active(109)[0].id,'new','expired speaker cannot block a fresh speaker');
q=new BubbleQueue();q.push(msg('edge'),107);
assert.equal(q.active(107)[0].until,108);
assert.deepEqual(q.active(108),[]);
console.log('bubble expiry: queued/active/ingress/invalid/near-expiry/fairness PASS');
