import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('../agent_world/web/stream-client.js',import.meta.url),'utf8');
const {EventLedger,BubbleQueue}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const ledger=new EventLedger(5);
const event=(n)=>({event_id:'e'+n,seq:n,occurred_at:n,payload:{text:'<script>data only</script>'}});
ledger.ingest([event(3),event(4)]);
ledger.ingest([event(1),event(2)],{historical:true});
assert.deepEqual(ledger.items().map(e=>e.seq),[1,2,3,4]);
assert.equal(ledger.ingest([event(3)]).length,0);
assert.equal(ledger.items()[0].historical,true);
ledger.ingest([event(5),event(6)]);assert.deepEqual(ledger.items().map(e=>e.seq),[2,3,4,5,6]);
const queue=new BubbleQueue({maxVisible:2,maxPending:6,perSubject:3});
queue.push({id:'a1',subject:'a',text:'one'});queue.push({id:'a2',subject:'a',text:'two'});queue.push({id:'b1',subject:'b',text:'other'});
assert.deepEqual(queue.active(0).map(x=>x.id),['a1','b1']);
assert.deepEqual(queue.active(1).map(x=>x.id),['a1','b1']);
assert.deepEqual(queue.active(5).map(x=>x.id),['a2']);
assert.equal(queue.push({id:'a1',subject:'a',text:'duplicate'}),false);
queue.clear();for(let n=0;n<7;n++)queue.push({id:'x'+n,subject:'x',text:'bounded'});
assert.equal(queue.pending.length,3);assert.equal(queue.dropped,4);
ledger.clear();assert.equal(ledger.items().length,0);
console.log('shared streams: ordering, dedup, bounded history, speaker queue, overflow, safe text PASS');
